apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: "${SERVICE_NAME}"
  labels:
    cloud.googleapis.com/location: "${REGION}"
  annotations:
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/description: Sample PHP-FPM Service
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        # Defines container startup order within multi-container service.
        # Below requires side-car "php-app" container to spin up before nginx proxy (entrypoint).
        # https://cloud.google.com/run/docs/configuring/containers#container-ordering
        run.googleapis.com/container-dependencies: '{"nginx":["php-app"]}'
    spec:
      containerConcurrency: 1
      containers:
        - name: nginx
          image: "${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/nginx"
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 256M
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8080
        - name: php-app
          image: "${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/php-app"
          env:
            - name: PORT
              value: "9000"
          resources:
            limits:
              cpu: 1000m
              # Explore more how to set memory limits in Cloud Run
              # https://cloud.google.com/run/docs/tips/general#optimize_concurrency
              # https://cloud.google.com/run/docs/configuring/services/memory-limits#optimizing
              memory: 335M
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 9000